export const ASSIGNMENT_STATUS = {
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
  SCANNED: "SCANNED",
  WORKING: "WORKING",
  DELIVERED: "DELIVERED",
  REJECT: "REJECT",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  TIMEOUT: "TIMEOUT",
} as const;

export const VEHICLE_JOB_STATUS = {
  WAIT: "WAIT",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
} as const;

export const TICKET_STATUS = {
  WAIT: "WAIT",
  IN_PROGRESS: "IN_PROGRESS",
  DELIVERED: "DELIVERED",
  REJECT: "REJECT",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
} as const;

export const ACTIVE_ASSIGNMENT_STATUSES: string[] = [
  ASSIGNMENT_STATUS.PENDING,
  ASSIGNMENT_STATUS.ACCEPTED,
  ASSIGNMENT_STATUS.SCANNED,
  ASSIGNMENT_STATUS.WORKING,
  ASSIGNMENT_STATUS.DELIVERED,
  ASSIGNMENT_STATUS.REJECT,
];

export const WORKING_ASSIGNMENT_STATUSES: string[] = [
  ASSIGNMENT_STATUS.SCANNED,
  ASSIGNMENT_STATUS.WORKING,
  ASSIGNMENT_STATUS.DELIVERED,
  ASSIGNMENT_STATUS.REJECT,
];

export const SCANNED_ASSIGNMENT_STATUSES: string[] = [
  ASSIGNMENT_STATUS.SCANNED,
  ASSIGNMENT_STATUS.WORKING,
  ASSIGNMENT_STATUS.DELIVERED,
  ASSIGNMENT_STATUS.REJECT,
  ASSIGNMENT_STATUS.COMPLETED,
];

export const FINISHED_ASSIGNMENT_STATUSES: string[] = [
  ASSIGNMENT_STATUS.PENDING,
  ASSIGNMENT_STATUS.ACCEPTED,
  ASSIGNMENT_STATUS.SCANNED,
  ASSIGNMENT_STATUS.WORKING,
  ASSIGNMENT_STATUS.DELIVERED,
  ASSIGNMENT_STATUS.REJECT,
  ASSIGNMENT_STATUS.COMPLETED,
];

export const TERMINAL_TICKET_STATUSES: string[] = [
  TICKET_STATUS.COMPLETED,
  TICKET_STATUS.CANCELLED,
];

export const TERMINAL_JOB_STATUSES: string[] = [
  VEHICLE_JOB_STATUS.COMPLETED,
  VEHICLE_JOB_STATUS.CANCELLED,
];
