export const ASSIGNMENT_STATUS = {
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
  SCANNED: "SCANNED",
  COUNTING: "COUNTING",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  TIMEOUT: "TIMEOUT",
} as const;

export const VEHICLE_JOB_STATUS = {
  WAIT: "WAIT",
  DISPATCH_NOW: "DISPATCH_NOW",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
} as const;

export const TICKET_STATUS = {
  WAIT: "WAIT",
  READY: "READY",
  IN_PROGRESS: "IN_PROGRESS",
  WAITING_VENDOR_CONFIRM: "WAITING_VENDOR_CONFIRM",
  COMPLETION_REJECTED: "COMPLETION_REJECTED",
  REOPEN: "REOPEN",
  CLOSED: "CLOSED",
  CANCELLED: "CANCELLED",
} as const;

export const ACTIVE_ASSIGNMENT_STATUSES: string[] = [
  ASSIGNMENT_STATUS.PENDING,
  ASSIGNMENT_STATUS.ACCEPTED,
  ASSIGNMENT_STATUS.SCANNED,
  ASSIGNMENT_STATUS.COUNTING,
];

export const WORKING_ASSIGNMENT_STATUSES: string[] = [
  ASSIGNMENT_STATUS.SCANNED,
  ASSIGNMENT_STATUS.COUNTING,
];

export const SCANNED_ASSIGNMENT_STATUSES: string[] = [
  ASSIGNMENT_STATUS.SCANNED,
  ASSIGNMENT_STATUS.COUNTING,
  ASSIGNMENT_STATUS.COMPLETED,
];

export const FINISHED_ASSIGNMENT_STATUSES: string[] = [
  ASSIGNMENT_STATUS.PENDING,
  ASSIGNMENT_STATUS.ACCEPTED,
  ASSIGNMENT_STATUS.SCANNED,
  ASSIGNMENT_STATUS.COUNTING,
  ASSIGNMENT_STATUS.COMPLETED,
];

export const TERMINAL_TICKET_STATUSES: string[] = [
  TICKET_STATUS.CLOSED,
  TICKET_STATUS.CANCELLED,
];

export const TERMINAL_JOB_STATUSES: string[] = [
  VEHICLE_JOB_STATUS.COMPLETED,
  VEHICLE_JOB_STATUS.CANCELLED,
];
