import { Prisma, PrismaClient } from "@prisma/client";

const masterRateSeeds: Prisma.MasterRateCreateInput[] = [
  {
    sourceRateId: 1,
    marketCode: "0000",
    weightRangeName: "1-25.0",
    weightMin: new Prisma.Decimal("0.00"),
    weightMax: new Prisma.Decimal("25.00"),
    stallRate: new Prisma.Decimal("1.50"),
    laborRate: new Prisma.Decimal("0.90"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 2,
    marketCode: "0000",
    weightRangeName: "25.1-50.0",
    weightMin: new Prisma.Decimal("25.00"),
    weightMax: new Prisma.Decimal("50.00"),
    stallRate: new Prisma.Decimal("3.50"),
    laborRate: new Prisma.Decimal("2.59"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 3,
    marketCode: "0000",
    weightRangeName: "50.1 ขึ้นไป",
    weightMin: new Prisma.Decimal("50.00"),
    weightMax: new Prisma.Decimal("5000.00"),
    stallRate: new Prisma.Decimal("6.00"),
    laborRate: new Prisma.Decimal("4.44"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 4,
    marketCode: "1111",
    weightRangeName: "0.5-5.0",
    weightMin: new Prisma.Decimal("0.00"),
    weightMax: new Prisma.Decimal("5.00"),
    stallRate: new Prisma.Decimal("0.20"),
    laborRate: new Prisma.Decimal("0.15"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 5,
    marketCode: "1111",
    weightRangeName: "5.1-15.0",
    weightMin: new Prisma.Decimal("5.00"),
    weightMax: new Prisma.Decimal("15.00"),
    stallRate: new Prisma.Decimal("0.57"),
    laborRate: new Prisma.Decimal("0.50"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 6,
    marketCode: "1111",
    weightRangeName: "15.1-29.9",
    weightMin: new Prisma.Decimal("15.00"),
    weightMax: new Prisma.Decimal("30.00"),
    stallRate: new Prisma.Decimal("0.75"),
    laborRate: new Prisma.Decimal("0.90"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 7,
    marketCode: "1111",
    weightRangeName: "30.0 ขึ้นไป",
    weightMin: new Prisma.Decimal("30.00"),
    weightMax: new Prisma.Decimal("5000.00"),
    stallRate: new Prisma.Decimal("2.25"),
    laborRate: new Prisma.Decimal("2.59"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 8,
    marketCode: "1113",
    weightRangeName: "0.5-5.0",
    weightMin: new Prisma.Decimal("0.00"),
    weightMax: new Prisma.Decimal("5.00"),
    stallRate: new Prisma.Decimal("0.20"),
    laborRate: new Prisma.Decimal("0.15"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 9,
    marketCode: "1113",
    weightRangeName: "5.1-15.0",
    weightMin: new Prisma.Decimal("5.00"),
    weightMax: new Prisma.Decimal("15.00"),
    stallRate: new Prisma.Decimal("0.57"),
    laborRate: new Prisma.Decimal("0.50"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 10,
    marketCode: "1113",
    weightRangeName: "15.1-29.9",
    weightMin: new Prisma.Decimal("15.00"),
    weightMax: new Prisma.Decimal("30.00"),
    stallRate: new Prisma.Decimal("0.75"),
    laborRate: new Prisma.Decimal("0.90"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 11,
    marketCode: "1113",
    weightRangeName: "30.0 ขึ้นไป",
    weightMin: new Prisma.Decimal("30.00"),
    weightMax: new Prisma.Decimal("5000.00"),
    stallRate: new Prisma.Decimal("2.25"),
    laborRate: new Prisma.Decimal("2.59"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 12,
    marketCode: "1112",
    weightRangeName: "0.5-5.0",
    weightMin: new Prisma.Decimal("0.00"),
    weightMax: new Prisma.Decimal("5.00"),
    stallRate: new Prisma.Decimal("0.20"),
    laborRate: new Prisma.Decimal("0.15"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 13,
    marketCode: "1112",
    weightRangeName: "5.1-15.0",
    weightMin: new Prisma.Decimal("5.00"),
    weightMax: new Prisma.Decimal("15.00"),
    stallRate: new Prisma.Decimal("0.57"),
    laborRate: new Prisma.Decimal("0.50"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 14,
    marketCode: "1112",
    weightRangeName: "15.1-29.9",
    weightMin: new Prisma.Decimal("15.00"),
    weightMax: new Prisma.Decimal("30.00"),
    stallRate: new Prisma.Decimal("0.75"),
    laborRate: new Prisma.Decimal("0.90"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 15,
    marketCode: "1112",
    weightRangeName: "30.0 ขึ้นไป",
    weightMin: new Prisma.Decimal("30.00"),
    weightMax: new Prisma.Decimal("5000.00"),
    stallRate: new Prisma.Decimal("2.25"),
    laborRate: new Prisma.Decimal("2.59"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 16,
    marketCode: "1129",
    weightRangeName: "0.5-5.0",
    weightMin: new Prisma.Decimal("0.00"),
    weightMax: new Prisma.Decimal("5.00"),
    stallRate: new Prisma.Decimal("0.20"),
    laborRate: new Prisma.Decimal("0.15"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 17,
    marketCode: "1129",
    weightRangeName: "5.1-15.0",
    weightMin: new Prisma.Decimal("5.00"),
    weightMax: new Prisma.Decimal("15.00"),
    stallRate: new Prisma.Decimal("0.57"),
    laborRate: new Prisma.Decimal("0.50"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 18,
    marketCode: "1129",
    weightRangeName: "15.1-29.9",
    weightMin: new Prisma.Decimal("15.00"),
    weightMax: new Prisma.Decimal("30.00"),
    stallRate: new Prisma.Decimal("0.75"),
    laborRate: new Prisma.Decimal("0.90"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 19,
    marketCode: "1129",
    weightRangeName: "30.0 ขึ้นไป",
    weightMin: new Prisma.Decimal("30.00"),
    weightMax: new Prisma.Decimal("5000.00"),
    stallRate: new Prisma.Decimal("2.25"),
    laborRate: new Prisma.Decimal("2.59"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 20,
    marketCode: "1409",
    weightRangeName: "0.5-5.0",
    weightMin: new Prisma.Decimal("0.00"),
    weightMax: new Prisma.Decimal("5.00"),
    stallRate: new Prisma.Decimal("0.20"),
    laborRate: new Prisma.Decimal("0.15"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 21,
    marketCode: "1409",
    weightRangeName: "5.1-15.0",
    weightMin: new Prisma.Decimal("5.00"),
    weightMax: new Prisma.Decimal("15.00"),
    stallRate: new Prisma.Decimal("0.57"),
    laborRate: new Prisma.Decimal("0.50"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 22,
    marketCode: "1409",
    weightRangeName: "15.1-29.9",
    weightMin: new Prisma.Decimal("15.00"),
    weightMax: new Prisma.Decimal("30.00"),
    stallRate: new Prisma.Decimal("0.75"),
    laborRate: new Prisma.Decimal("0.90"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 23,
    marketCode: "1409",
    weightRangeName: "30.0 ขึ้นไป",
    weightMin: new Prisma.Decimal("30.00"),
    weightMax: new Prisma.Decimal("5000.00"),
    stallRate: new Prisma.Decimal("2.25"),
    laborRate: new Prisma.Decimal("2.59"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 24,
    marketCode: "1412",
    weightRangeName: "0.5-5.0",
    weightMin: new Prisma.Decimal("0.00"),
    weightMax: new Prisma.Decimal("5.00"),
    stallRate: new Prisma.Decimal("0.20"),
    laborRate: new Prisma.Decimal("0.15"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 25,
    marketCode: "1412",
    weightRangeName: "5.1-15.0",
    weightMin: new Prisma.Decimal("5.00"),
    weightMax: new Prisma.Decimal("15.00"),
    stallRate: new Prisma.Decimal("0.57"),
    laborRate: new Prisma.Decimal("0.50"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 26,
    marketCode: "1412",
    weightRangeName: "15.1-29.9",
    weightMin: new Prisma.Decimal("15.00"),
    weightMax: new Prisma.Decimal("30.00"),
    stallRate: new Prisma.Decimal("0.75"),
    laborRate: new Prisma.Decimal("0.90"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 27,
    marketCode: "1412",
    weightRangeName: "30.0 ขึ้นไป",
    weightMin: new Prisma.Decimal("30.00"),
    weightMax: new Prisma.Decimal("5000.00"),
    stallRate: new Prisma.Decimal("2.25"),
    laborRate: new Prisma.Decimal("2.59"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 28,
    marketCode: "1110",
    weightRangeName: "0.5-5.0",
    weightMin: new Prisma.Decimal("0.00"),
    weightMax: new Prisma.Decimal("5.00"),
    stallRate: new Prisma.Decimal("0.20"),
    laborRate: new Prisma.Decimal("0.15"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 29,
    marketCode: "1110",
    weightRangeName: "5.1-15.0",
    weightMin: new Prisma.Decimal("5.00"),
    weightMax: new Prisma.Decimal("15.00"),
    stallRate: new Prisma.Decimal("0.57"),
    laborRate: new Prisma.Decimal("0.50"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 30,
    marketCode: "1110",
    weightRangeName: "15.1-29.9",
    weightMin: new Prisma.Decimal("15.00"),
    weightMax: new Prisma.Decimal("30.00"),
    stallRate: new Prisma.Decimal("0.75"),
    laborRate: new Prisma.Decimal("0.90"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 31,
    marketCode: "1110",
    weightRangeName: "30.0 ขึ้นไป",
    weightMin: new Prisma.Decimal("30.00"),
    weightMax: new Prisma.Decimal("5000.00"),
    stallRate: new Prisma.Decimal("2.25"),
    laborRate: new Prisma.Decimal("2.59"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 32,
    marketCode: "1128",
    weightRangeName: "1-25.0",
    weightMin: new Prisma.Decimal("0.00"),
    weightMax: new Prisma.Decimal("25.00"),
    stallRate: new Prisma.Decimal("1.50"),
    laborRate: new Prisma.Decimal("0.90"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 33,
    marketCode: "1128",
    weightRangeName: "25.1-50.0",
    weightMin: new Prisma.Decimal("25.00"),
    weightMax: new Prisma.Decimal("50.00"),
    stallRate: new Prisma.Decimal("3.50"),
    laborRate: new Prisma.Decimal("2.59"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 34,
    marketCode: "1128",
    weightRangeName: "50.1 ขึ้นไป",
    weightMin: new Prisma.Decimal("50.00"),
    weightMax: new Prisma.Decimal("5000.00"),
    stallRate: new Prisma.Decimal("6.00"),
    laborRate: new Prisma.Decimal("4.44"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 35,
    marketCode: "1120",
    weightRangeName: "1-25.0",
    weightMin: new Prisma.Decimal("0.00"),
    weightMax: new Prisma.Decimal("25.00"),
    stallRate: new Prisma.Decimal("1.50"),
    laborRate: new Prisma.Decimal("0.90"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 36,
    marketCode: "1120",
    weightRangeName: "25.1-50.0",
    weightMin: new Prisma.Decimal("25.00"),
    weightMax: new Prisma.Decimal("50.00"),
    stallRate: new Prisma.Decimal("3.50"),
    laborRate: new Prisma.Decimal("2.59"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 37,
    marketCode: "1120",
    weightRangeName: "50.1 ขึ้นไป",
    weightMin: new Prisma.Decimal("50.00"),
    weightMax: new Prisma.Decimal("5000.00"),
    stallRate: new Prisma.Decimal("6.00"),
    laborRate: new Prisma.Decimal("4.44"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 38,
    marketCode: "1125",
    weightRangeName: "1-25.0",
    weightMin: new Prisma.Decimal("0.00"),
    weightMax: new Prisma.Decimal("25.00"),
    stallRate: new Prisma.Decimal("1.50"),
    laborRate: new Prisma.Decimal("0.90"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 39,
    marketCode: "1125",
    weightRangeName: "25.1-50.0",
    weightMin: new Prisma.Decimal("25.00"),
    weightMax: new Prisma.Decimal("50.00"),
    stallRate: new Prisma.Decimal("3.50"),
    laborRate: new Prisma.Decimal("2.59"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 40,
    marketCode: "1125",
    weightRangeName: "50.1 ขึ้นไป",
    weightMin: new Prisma.Decimal("50.00"),
    weightMax: new Prisma.Decimal("5000.00"),
    stallRate: new Prisma.Decimal("6.00"),
    laborRate: new Prisma.Decimal("4.44"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 41,
    marketCode: "1126",
    weightRangeName: "1-25.0",
    weightMin: new Prisma.Decimal("0.00"),
    weightMax: new Prisma.Decimal("25.00"),
    stallRate: new Prisma.Decimal("1.50"),
    laborRate: new Prisma.Decimal("0.90"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 42,
    marketCode: "1126",
    weightRangeName: "25.1-50.0",
    weightMin: new Prisma.Decimal("25.00"),
    weightMax: new Prisma.Decimal("50.00"),
    stallRate: new Prisma.Decimal("3.50"),
    laborRate: new Prisma.Decimal("2.59"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 43,
    marketCode: "1126",
    weightRangeName: "50.1 ขึ้นไป",
    weightMin: new Prisma.Decimal("50.00"),
    weightMax: new Prisma.Decimal("5000.00"),
    stallRate: new Prisma.Decimal("6.00"),
    laborRate: new Prisma.Decimal("4.44"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 44,
    marketCode: "1123",
    weightRangeName: "1-25.0",
    weightMin: new Prisma.Decimal("0.00"),
    weightMax: new Prisma.Decimal("25.00"),
    stallRate: new Prisma.Decimal("1.00"),
    laborRate: new Prisma.Decimal("0.90"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: new Date("2025-12-26T00:00:00.000+07:00"),
  },
  {
    sourceRateId: 45,
    marketCode: "1123",
    weightRangeName: "25.1-50.0",
    weightMin: new Prisma.Decimal("25.00"),
    weightMax: new Prisma.Decimal("50.00"),
    stallRate: new Prisma.Decimal("3.50"),
    laborRate: new Prisma.Decimal("2.59"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 46,
    marketCode: "1123",
    weightRangeName: "50.1 ขึ้นไป",
    weightMin: new Prisma.Decimal("50.00"),
    weightMax: new Prisma.Decimal("5000.00"),
    stallRate: new Prisma.Decimal("6.00"),
    laborRate: new Prisma.Decimal("4.44"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 47,
    marketCode: "1124",
    weightRangeName: "1-25.0",
    weightMin: new Prisma.Decimal("0.00"),
    weightMax: new Prisma.Decimal("25.00"),
    stallRate: new Prisma.Decimal("1.50"),
    laborRate: new Prisma.Decimal("0.90"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 48,
    marketCode: "1124",
    weightRangeName: "25.1-50.0",
    weightMin: new Prisma.Decimal("25.00"),
    weightMax: new Prisma.Decimal("50.00"),
    stallRate: new Prisma.Decimal("3.50"),
    laborRate: new Prisma.Decimal("2.59"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 49,
    marketCode: "1124",
    weightRangeName: "50.1 ขึ้นไป",
    weightMin: new Prisma.Decimal("50.00"),
    weightMax: new Prisma.Decimal("5000.00"),
    stallRate: new Prisma.Decimal("6.00"),
    laborRate: new Prisma.Decimal("4.44"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 50,
    marketCode: "1411",
    weightRangeName: "1-25.0",
    weightMin: new Prisma.Decimal("0.00"),
    weightMax: new Prisma.Decimal("25.00"),
    stallRate: new Prisma.Decimal("1.50"),
    laborRate: new Prisma.Decimal("0.90"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 51,
    marketCode: "1411",
    weightRangeName: "25.1-50.0",
    weightMin: new Prisma.Decimal("25.00"),
    weightMax: new Prisma.Decimal("50.00"),
    stallRate: new Prisma.Decimal("3.50"),
    laborRate: new Prisma.Decimal("2.59"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 52,
    marketCode: "1411",
    weightRangeName: "50.1 ขึ้นไป",
    weightMin: new Prisma.Decimal("50.00"),
    weightMax: new Prisma.Decimal("5000.00"),
    stallRate: new Prisma.Decimal("6.00"),
    laborRate: new Prisma.Decimal("4.44"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 53,
    marketCode: "1123-1",
    weightRangeName: "1-25.0",
    weightMin: new Prisma.Decimal("0.00"),
    weightMax: new Prisma.Decimal("25.00"),
    stallRate: new Prisma.Decimal("1.50"),
    laborRate: new Prisma.Decimal("0.90"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 54,
    marketCode: "1123-1",
    weightRangeName: "25.1-50.0",
    weightMin: new Prisma.Decimal("25.00"),
    weightMax: new Prisma.Decimal("50.00"),
    stallRate: new Prisma.Decimal("3.50"),
    laborRate: new Prisma.Decimal("2.59"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
  {
    sourceRateId: 55,
    marketCode: "1123-1",
    weightRangeName: "50.1 ขึ้นไป",
    weightMin: new Prisma.Decimal("50.00"),
    weightMax: new Prisma.Decimal("5000.00"),
    stallRate: new Prisma.Decimal("6.00"),
    laborRate: new Prisma.Decimal("4.44"),
    status: 1,
    sourceCreatedAt: null,
    sourceUpdatedAt: null,
  },
];

// Function seed ข้อมูล master_rate จาก master rate list ลง DB
export async function seedMasterRates(prisma: PrismaClient): Promise<void> {
  const syncedAt = new Date();

  await prisma.$transaction(
    masterRateSeeds.map((rate) =>
      prisma.masterRate.upsert({
        where: {
          sourceRateId: rate.sourceRateId,
        },
        update: {
          marketCode: rate.marketCode,
          weightRangeName: rate.weightRangeName,
          weightMin: rate.weightMin,
          weightMax: rate.weightMax,
          stallRate: rate.stallRate,
          laborRate: rate.laborRate,
          status: rate.status,
          sourceCreatedAt: rate.sourceCreatedAt,
          sourceUpdatedAt: rate.sourceUpdatedAt,
          syncedAt,
        },
        create: {
          ...rate,
          syncedAt,
        },
      }),
    ),
  );

  console.log(`Seeded ${masterRateSeeds.length} master_rate records.`);
}
