-- Add device binding + terminal grace-period support to driver_sessions.
-- device_id: UUID (random, generated by Driver Web, persisted in browser storage) used to enforce
-- the "max 2 active devices per vehicle job" limit. Nullable to keep existing/legacy rows valid.
-- read_only_until: set only when a session is revoked because the vehicle job reached a terminal
-- status (COMPLETED/CANCELLED); lets the same session keep reading the final snapshot for a grace
-- window instead of getting revoked (401) immediately. Sessions revoked for other reasons (e.g. the
-- same device rescanning the QR and rotating its session) leave this column NULL, so they do not get
-- read access back.

ALTER TABLE "driver_sessions" ADD COLUMN "device_id" VARCHAR(255);
ALTER TABLE "driver_sessions" ADD COLUMN "read_only_until" TIMESTAMP(3);

CREATE INDEX "driver_sessions_ticket_job_id_device_id_idx" ON "driver_sessions"("ticket_job_id", "device_id");
